"""add phone number

Revision ID: 87789d8f3803
Revises: 57674e31bed6
Create Date: 2023-10-23 09:56:12.320769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87789d8f3803'
down_revision: Union[str, None] = '57674e31bed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('votes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'phone_number')
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
